### ISSUE TITLE
[Bug]: Perception CUDA out of memory

### ISSUE THREAD

**Issue by okrusch** [una-auxme/paf23#102]
### Current Behavior

When i try to run the model of the vision node on CUDA, i get a CUDA out of memory error.

### Expected Behavior

It should be possible to use CUDA if available.

### How to reproduce the issue

For now the device is set to CPU, but you can change it in vision_node.py

The issue includes updating the torch and cuda version

**Comment by MaxJa4** [comment]
Does this also happen when using FP16 precision for inference? Or is the error occurring despite having enough VRAM?
