### ISSUE TITLE
[Bug]: Can't publish current_pos in dev launch, because OpenDrive doesn't get published

### ISSUE THREAD

**Issue by robertik10** [una-auxme/paf23#121]
### Current Behavior

current_pos doesn't get published in dev launch, because OpenDrive doesn't get published
![image](https://github.com/una-auxme/paf23/assets/58191510/63a97ccb-2cf7-438a-8373-d8c7c5d055b7)
Coordinate Transformation needs reference values to perform a transformation, which are usually published by OpenDrive and filtered out by the `get_geoRef` method  inside the `Perception/src/Position_Publisher_Node.py`.
OpenDrive doesn't get published in the dev launch which results in no possible way of Coordinate Transformation.
-> either build an OpenDrive publisher for the dev launch or find other workaround

### Expected Behavior

current_pos should be getting published

### How to reproduce the issue

start the project in dev launch mode

**Comment by samuelkuehnel** [comment]
can be set to done?@robertik10
