### ISSUE TITLE
[Bug]: current_heading is not calculated correctly

### ISSUE THREAD

**Issue by robertik10** [una-auxme/paf23#151]
### Current Behavior

Heading somehow jumps between two values, while it should be a continuous plot of data.

### Expected Behavior

Should be a continuous plot of data that shows the rotation around the z axis as an angle in radians.
If the car is driving in circles it should publish a current heading that looks like a sin curve.

### How to reproduce the issue

Heading somehow jumps between two values even when the car is driving full circles.

**Comment by hellschwalex** [comment]
Since both Steering-Algorithms highly depend on current_heading being published correctly, i will look into this bug aswell!

**Comment by robertik10** [comment]
The Heading fix is fully functional in the Kalman Filter branch #150, which will hopefully pass the pull request soon.
To work with the fix you will need to rebase your current branch to the main branch or you could keep using the yaw as your heading for your testing purposes for now. :))
