### ISSUE TITLE
Verify that the `control_loop_rate` of `0.3` for the `ACC` is the best choice.

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf23#255]
https://github.com/una-auxme/paf23/blob/8cb891c282cc51a2b936f3c9183940ea43c1e4d8/code/planning/launch/planning.launch#L6-L9

**Comment by JulianTrommer** [comment]
Fixed to 20 fps [here](https://github.com/una-auxme/paf23/blob/79d71b1687e5c4c5b698f58b90415823fa326607/code/planning/launch/planning.launch#L3C1-L12C12)
