### ISSUE TITLE
"Vehicle_controller" control_loop_rate is set to 0.1. However, this contradicts the comment that it should be 0.05s

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf23#258]
https://github.com/una-auxme/paf23/blob/8cb891c282cc51a2b936f3c9183940ea43c1e4d8/code/acting/launch/acting.launch#L21-L24

Maybe, the vehicle_controller control_loop_rate should be the frame rate of the simulator?

**Comment by JulianTrommer** [comment]
#268 Fixed this issue.
