### ISSUE TITLE
[Feature]: Rework commit message hook

### ISSUE THREAD

**Issue by JulianTrommer** [una-auxme/paf23#273]
### Description

See /build/config-comlipy.yml

**Comment by ll7** [comment]
The hooks are only installed if we continue to use b5. 

https://github.com/una-auxme/paf23/blob/ad7767abb29fb9a78c2b2de152df3033dbe02fde/build/Taskfile#L18-L23

https://github.com/una-auxme/paf23/blob/ad7767abb29fb9a78c2b2de152df3033dbe02fde/build/Taskfile#L66-L70

Influences #274

**Comment by ll7** [comment]
Comlipy feels a little bit outdated:
https://gitlab.com/slashplus-build/comlipy/
https://gitlab.com/slashplus-build/comlipy/tree/master/docs
https://gitlab.com/slashplus-build/comlipy/-/blob/master/docs/reference-rules.md

We could set the level to `warning` which corresponds to level 1.
