### ISSUE TITLE
[Bug]: `Bump version and push tag` fails.

### ISSUE THREAD

**Issue by ll7** [una-auxme/paf23#48]
### Current Behavior

example where it fails: https://github.com/una-auxme/paf23/actions/runs/6855063779/job/18639329764#step:6:109

```
Run mathieudutour/github-tag-action@v6.1
  with:
    github_token: ***
    release_branches: main
    default_bump: patch
    default_prerelease_bump: prerelease
    tag_prefix: v
    create_annotated_tag: false
    fetch_all_tags: false
    dry_run: false
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: una-auxme/paf[2](https://github.com/una-auxme/paf23/actions/runs/6855063779/job/18639329764#step:6:2)[3](https://github.com/una-auxme/paf23/actions/runs/6855063779/job/18639329764#step:6:3)
Previous tag was v0.3[7](https://github.com/una-auxme/paf23/actions/runs/6855063779/job/18639329764#step:6:7).2, previous version was 0.37.2.
Analyzing commit: Reverted repositories back to working commit
The commit should not trigger a release
Analyzing commit: 232 Reverted repositories back to working commit (#233)

...

4 feature pylot planning paf21/2 perception
The commit should not trigger a release
Analysis of 20 commits complete: no release
New version is 0.37.3.
New tag after applying prefix is v0.37.3.
Changelog is ### [0.37.3](https://github.com/una-auxme/paf23/compare/v0.37.2...v0.37.3) (2023-11-13)

.
Error: Resource not accessible by integration
```

Action that fails:

https://github.com/una-auxme/paf23/blob/f484bafcfc8b11729ea6a2f31305783952d6282d/.github/workflows/build.yml#L41-L48

---

My personal interpretation:

- this action tries to analyze the commit history and decides based on the commit messages if a new version of the repository with a dedicated version tag is justified.
- when a version is justified, the access is denied towards this action to create a new tag in our repository
- the reason could be, that the github_token is not available on the local ci/cd PC `github_token: ${{ secrets.GITHUB_TOKEN }}`

### Expected Behavior

Either fix the action permissions or remove the action because we don't want to create arbitrary GitHub tags.

I assigned @robertik10 , because the number of tags affects the “tidiness” of the repository and I assigned @samuelkuehnel and @MaxJa4 because it is part of the build process.

### How to reproduce the issue

I have no idea how you can force this action to create a new version. Maybe ask @JulianTrommer or @nylser .

**Comment by MaxJa4** [comment]
Samuel and I didn't see a need or use for the tags, which get created automatically.
If at all, it would make sense to manually create a new tag with every sprint (after PR merging) or after a milestone is reached.
--> Removed it in #57
