### ISSUE TITLE
[Feature]: ACTING - Compare (planned) trajectory with actual driven trajectory

### ISSUE THREAD

**Issue by hellschwalex** [una-auxme/paf23#52]
### Description

Since the Acting components neither seem to follow a trajectory closely nor react to other inputs (seemingly), we will check, if and how the current Acting components generally react to inputs.
The planned trajectory to be followed is already visible, so we will start by checking how closely the choosen actions match the trajectory-following.

### Definition of Done

- Create a small documentation of the results found
- MAYBE: Fix some faults founds

**Comment by hellschwalex** [comment]
As #51 took more time than foreseen, I will take care of this on monday morning.

**Comment by robertik10** [comment]
I am going to finish looking into this issue tomorrow (Sunday) and will hopefully be able to do a PR Sunday afternoon.
