### ISSUE TITLE
[Feature]: Test PyLot and Coco-Models for Object-Detection

### ISSUE THREAD

**Issue by okrusch** [una-auxme/paf23#54]
### Description

- [x] PyLot's models (Tensorflow) for Object-Detection ito see if it would make a good replacement
- [x] Measure processing time and document results (along with images)
- [x] Evaluate similar Coco PyTorch models for comparison
- [x] Evaluate YOLOv8 for comparison
- [x] Summarize findings und create documentation

### Definition of Done

- We can tell if PyLot is good fit for our project, or not
- We know which PyLot model would work best
- We know which PyTorch model would work best
- We know if YOLOv8 would work well

**Comment by MaxJa4** [comment]
Evaluated the following models in a small standalone project.
Used 8 images for each model to check out different scenarios.
Also measured execution time.

1. PyTorch:
- fasterrcnn_mobilenet_v3_large_320_fpn
- fasterrcnn_resnet50_fpn_v2
- retinanet_resnet50_fpn_v2

2. TensorFlow (Pylot):
- faster-rcnn
- ssdlite-mobilenet-v2
- ssd-mobilenet-fpn-640
- ssd-mobilenet-v1
- ssd-mobilenet-v1-fpn

3. YOLOv8
---
Will add experiment documentation with results soon.
