### ISSUE TITLE
[Feature]: Cleaning up the github repository

### ISSUE THREAD

**Issue by robertik10** [una-auxme/paf23#55]
### Content:
Cleaning up the github repository

### Definition of Done

- [x]  merging existing PRs
- [x]  Deleting [old branches](https://github.com/una-auxme/paf23/branches/stale)
- [x]  cleaning up repository, so every file is in the correct folder (research)
- [x]  linking all new files in the documentation

**Comment by MaxJa4** [comment]
The old [tags](https://github.com/una-auxme/paf23/tags) have already been removed by Samuel and me (keep the v0.0.1 there, it's from us).
[Old branches](https://github.com/una-auxme/paf23/branches/stale) from PAF22 are still present and need to be removed please :)

**Comment by robertik10** [comment]
Thanks for the info! All the old branches have been removed :)
