### ISSUE TITLE
[Feature]: Set up DVC/LFS for PAF23

### ISSUE THREAD

**Issue by MaxJa4** [una-auxme/paf23#62]
### Description

PAF22-Docs for DVC: [Link](https://github.com/una-auxme/paf23/blob/main/doc/02_development/11_dvc.md)
Official Docs (about the remote storage): [Link](https://dvc.org/doc/user-guide/data-management/remote-storage)
GitHub LFS Docs: [Link](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)

DVC was used in PAF22 for storing ML datasets and trained models to iterate/switch faster without commits or PRs and is optimized for large file sizes.

It was used in PAF22 together with Google Drive, where they used a dedicated PAF account (@ll7 has the credentials).

LFS doesn't need Google Drive or similar, it can use GitHub itself (< 2GB per file).

### Definition of Done

- Handling ML datasets & trained models is solved

**Comment by ll7** [comment]
Additional information: The Google Drive account was created as a dedicated PAF-DVC account. I have the credentials, and you can use the account if you like.

**Comment by MaxJa4** [comment]
Great, thanks. Lets discuss this in the next review/planning.

**Comment by MaxJa4** [comment]
Hint: Installing DVC with `pip install dvc dvc-gdrive` like suggested in the PAF22 docs, installs a new DVC version which [doesn't work](https://github.com/iterative/dvc/issues/10030) for new repositories (so for us).
Use an older version for now: `pip install dvc==3.23.0 dvc-gdrive`
