### ISSUE TITLE
[Bug]: Agent doesnt drive after update to Leaderboard 2.0

### ISSUE THREAD

**Issue by samuelkuehnel** [una-auxme/paf23#76]
### Current Behavior

After update to Leaderboard 2.0 in #37 the agent doesnt start to drive. 
Apparantly the start routine is not executed.

### Expected Behavior

- [ ] Agent drives as already known from the previous version

### How to reproduce the issue

- Get branch ```37-bug-update-docker-image-for-carla-simulator-to-fix-build-process```
- Run ```b5 install``` and ```b5 run```

**Comment by samuelkuehnel** [comment]
Current problem is that the coordinates recieved from our GNSS do not match the coordinates expected from the route:

![Image](https://github.com/una-auxme/paf23/assets/51356601/5158b38a-0b1d-4221-8c75-2b36444c9d2f)


In the leaderboard 1.0 the coordinates match.



![Image](https://github.com/una-auxme/paf23/assets/51356601/062bcbc8-997f-4634-b376-9ba211b9ac13)


It seems like the calculations done in `coordinate_transformation.py` are wrong as they depend on the map.

**Comment by samuelkuehnel** [comment]
The values received from our GNSS seem to be different anyway in the new leaderboard version: 

Graph from leaderboard 1:

![Image](https://github.com/una-auxme/paf23/assets/51356601/0700b164-a6f0-48fb-9dc3-5c693ebc0d71)

Graph from leaderboard 2:


![Image](https://github.com/una-auxme/paf23/assets/51356601/8996c8a6-7ee9-4880-a831-d238344c56e3)

**Comment by samuelkuehnel** [comment]
**Update**: The reason for this was found in the ```coordinate_transformation.py``` file. The calculation there is built on reference coordinates that seem to be the map origin (0, 0, 0). For _Town 12_ the reference coordinates were set to different values, what produced wrong coordinates in the new leaderboard.

Now the calculated coordinates are calculated correctly and a trajectory is created. 

However the car still doesn't follow the trajectory and steers onto the sidewalk where it gets stuck. Next step is to compare the new trajectory to the old one to verify if the issue is located in the calculation of the trajectory or in the acting components

**Comment by MaxJa4** [comment]
> Now the calculated coordinates are calculated correctly and a trajectory is created.

Can this be calculated independent from the map or is it hardcoded now?
Since we have Town 12 & 13 to test drive and unknown T14 for validation.
